on: [push]

name: Build Docker images

jobs:
  build_ort:
    name: ort
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3
      with:
        submodules: recursive

    - runs: cd latest/ort

    - name: Build Docker Images with Oss Review Toolkit 
      uses: philips-software/docker-ci-scripts@v3.1.0
      with:
        dockerfile: .
        image-name: ort
        tags: latest 2020-10-07
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
