on: [push]

name: Build Docker images

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
  DOCKER_ORGANIZATION: philipssoftware
  GITHUB_ORGANIZATION: philips-software

jobs:
  build_ort:
    name: ort
    runs-on: ubuntu-latest
    container: docker:20.10.2-git

    steps:
    - uses: actions/checkout@v2.3.3
      with:
        submodules: recursive
    - name: check version docker
      run: docker --version
    - name: Build Docker Images with Oss Review Toolkit 
      uses: philips-software/docker-ci-scripts@update-docker
      with:
        dockerfile: latest/ort
        image-name: ort
        tags: latest 2021-01-19
